Feature/update astarte sdk version
edgehog-device-manager/edgehog-esp32-device pull request #101
Opened 2024-08-07 10:48 UTC by lucaato

Update of the edgehog example app and updated the astarte device sdk dependency version

2024-08-19 10:22 UTC, harlem88 reviewed
Add Bump of Astarte SDK to the Changelog

2024-08-19 13:52 UTC, lucaato commented
> Add Bump of Astarte SDK to the Changelog

I replaced the unreleased line about the update to `1.2.0`

2024-08-20 14:53 UTC, harlem88 requested changes

2024-08-20 14:53 UTC, harlem88 commented on examples/edgehog_app/main/src/wifi.c
> + * - we failed to connect after the maximum amount of retries */
```suggestion
 * - we failed to connect after the maximum amount of retries 
 */
```

2024-08-26 09:09 UTC, sorru94 requested changes

2024-08-26 09:09 UTC, sorru94 commented on CHANGELOG.md
Remove the `Makefile` and `component.mk` files from the example directory. They are not used anymore.

2024-08-26 09:09 UTC, sorru94 commented on CHANGELOG.md
Add two partitions to the `edgehog_partition_example.csv` partition table. One for hedgehog and another for astarte. Then use them in the SDK and Edgehog respectively.
```
astarte,  data, nvs,     ,        200K,
edgehog,  data, nvs,     ,        200K,
```

2024-08-26 09:09 UTC, sorru94 commented on examples/edgehog_app/main/main.c
>      ESP_ERROR_CHECK(ret);
Add the following (also add the defines in the header of the `example_task.h`.
```
    ESP_ERROR_CHECK(nvs_flash_init_partition(ASTARTE_PARTITION_NAME));
    ESP_ERROR_CHECK(nvs_flash_init_partition(EDGEHOG_PARTITION_NAME));
```

2024-08-26 09:09 UTC, sorru94 commented on examples/edgehog_app/main/Kconfig.projbuild
> +menu "WiFi configuration"
```suggestion

config CREDENTIALS_SECRET
    string "Credentials secret"
    default ""
    help
        Astarte device credential secret, generated when the device is added on an Astarte
        instance.

config DEVICE_ID
    string "Device hardware ID"
    default ""
    help
        Astarte device hardware id, generated when the device is added on an Astarte instance.

menu "WiFi configuration"
```

2024-08-26 09:09 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
>  #include <astarte_credentials.h>
One of the main issues with this example is that it does not explicitly wait for the Astarte device SDK to be connected before starting Edgehog.
To do so, the following user data can be added to the Astarte device SDK:
```
typedef struct
{
    TaskHandle_t xMainTaskHandle;
    edgehog_device_handle_t edgehog_device;
} astarte_device_user_data_t;
```
The initialization of the Astarte device and Edgehog devices should be performed in the same function as they are intertwined. 
I suggest creating an `initialize_devices` function that properly initializes both devices.
You can see the function I refer to in #100.

2024-08-26 15:16 UTC, lucaato commented on examples/edgehog_app/main/src/example_task.c
>  #include <astarte_credentials.h>
Is this needed? Both devices are indeed initialized at the same time without waiting but I do wait before starting the edgehog device on line 106:
```c
// Wait until the Astarte device is connected
(void) ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
ESP_LOGI(TAG, "Astarte device started")
```
This gives more freedom to a user copying the example to still use the Astarte device after edgehog initialization, which I think is a supported use case.
If the wait code is not correct I would still like to keep it in the main function to ease integration with other code on the user part.

2024-08-28 07:24 UTC, harlem88 requested changes

2024-08-28 07:24 UTC, harlem88 commented on examples/edgehog_app/edgehog_partition_example.csv
> -nvs,      data, nvs,     0x9000,  0x4000,
Don't remove the nvs default partition, it is used by `default components` for instance the `wifi` component use it to store the ssid and psw for connecting to the wifi access point.

2024-08-28 08:54 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +        .callbacks_user_data = notify_handle,
Add here the credential secret and device ID from the Kconfig.
Then remove the `astarte_device_get_encoded_id`

2024-08-28 08:54 UTC, sorru94 commented on examples/edgehog_app/main/Kconfig.projbuild
> +config CREDENTIALS_SECRET
Thinking about it again it might be clearer to place those in an Astarte device configuration menu.
What do you think?

2024-08-28 08:54 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
>  #include <astarte_credentials.h>
As we discussed offline this is good but remember to use the give function before the take.

2024-08-28 09:06 UTC, lucaato commented on examples/edgehog_app/main/src/example_task.c
>  #include <astarte_credentials.h>
Yes it is in the connection callback `examples/edgehog_app/main/src/example_task.c` line 234.

2024-08-28 10:46 UTC, lucaato commented on examples/edgehog_app/main/Kconfig.projbuild
> +config CREDENTIALS_SECRET
It makes sense, I'll do this.

2024-08-29 10:37 UTC, harlem88 reviewed
Resolve the DCO CI failure

2024-08-30 07:26 UTC, sorru94 commented on examples/edgehog_app/main/main.c
> +    esp_log_level_set("ASTARTE_PAIRING", ESP_LOG_DEBUG);
This should be removed in the final version of the example.

2024-08-30 07:26 UTC, sorru94 commented on examples/edgehog_app/main/main.c
> +static const char *TAG = "example main";
For most tags we use all caps. I you want to shorten it and remove the edgehog prefix I agree. But I would keep it coherent with the rest of the library.

2024-08-30 07:26 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +#include "sdkconfig.h"
What is this for?

2024-08-30 07:26 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +        vTaskDelay(xDelay);
Leave the comment and remove the `vTaskDelay`

2024-08-30 07:26 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +    // notifying the passed task
```suggestion
    // Unlocking the example task
```

2024-08-30 07:26 UTC, sorru94 commented on examples/edgehog_app/sdkconfig.defaults
> +CONFIG_ESP_HTTPS_OTA_ALLOW_HTTP=n
The new values for the three configuration options are in conflict with each other. 
The first one enables the insecure TLS options. 
The second one ignores TLS certificate validation and can only be enabled if the first one is enabled.
The third one allows the use of HTTP during OTA operations instead of HTTPS.
Why change them in the first place?

2024-09-03 10:55 UTC, lucaato commented on examples/edgehog_app/main/src/example_task.c
> +#include "sdkconfig.h"
removed

2024-09-03 10:56 UTC, lucaato commented on examples/edgehog_app/main/src/example_task.c
> +        vTaskDelay(xDelay);
isn't it better to add a delay to the loop ?

2024-09-03 10:59 UTC, lucaato commented on examples/edgehog_app/sdkconfig.defaults
> +CONFIG_ESP_HTTPS_OTA_ALLOW_HTTP=n
rolled back the change

2024-09-03 12:21 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +#include "sdkconfig.h"
This should not be necessary. All the selections of the sdkconfig are available without that define.

2024-09-03 12:23 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +        vTaskDelay(xDelay);
The `vTaskDelay` was not added here following a discussion with @harlem88 a long time ago. 
The comment is more explicative. The user should decide its programming approach to avoid starvation.

2024-09-03 12:38 UTC, lucaato commented on examples/edgehog_app/main/src/example_task.c
> +        vTaskDelay(xDelay);
ok, i don't fully get it but ok :D

2024-09-03 12:55 UTC, sorru94 commented on .github/workflows/build.yaml
> +          - "5.1"
```suggestion
          - "4.4"
          - "5.0"
          - "5.1"
          - "5.2"
          - "5.3"
```

2024-09-03 12:55 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +        return;
Do not return from a task. Use `vTaskDelete(NULL);`
Or assert if you want to crash. I suggest using `vTaskDelete(NULL);` with an error. As this will only stop the application and not force a restart of the device making it easier to read.

2024-09-03 12:55 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +    while (true) {
```suggestion
    while (true) {
        // In this example this task is running with the lower priority and does not starve
        // the mcu thanks to time slicing.
        // If in your code you want to run this task with a higher priority make sure not to
        // starve the mcu by placing vTaskDelay() in here.
```

2024-09-03 13:21 UTC, sorru94 requested changes

2024-09-03 13:21 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +    edgehog_device_handle_t edgehog_device = edgehog_device_init(astarte_handle);
If this is a local variable it should be passed as the `current_task_handle` variable. Otherwise do not declare it twice.

2024-09-03 13:38 UTC, sorru94 requested changes

2024-09-03 13:38 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +    edgehog_device_handle_t edgehog_device = edgehog_device_init(astarte_handle);
Still overwriting.

2024-09-03 14:21 UTC, harlem88 approved these changes

2024-09-03 14:29 UTC, sorru94 approved these changes

2024-09-03 14:29 UTC, merged