Refactor documentation workflow
edgehog-device-manager/edgehog-esp32-device pull request #108
Opened 2024-12-10 13:50 UTC by sorru94

2024-12-10 16:31 UTC, harlem88 requested changes

2024-12-10 16:31 UTC, harlem88 commented on .github/workflows/docs-workflow.yaml
> +        wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
Why are you downloading `doxygen` binary instead of to install it?

https://github.com/astarte-platform/astarte-device-sdk-esp32/blob/05a36a607fda404a5f86248a6b76dbfad87e73a5/.github/workflows/docs-workflow.yaml#L51

2024-12-10 17:15 UTC, sorru94 commented on .github/workflows/docs-workflow.yaml
> +        wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
Because the version that can be downloaded using apt on Ubuntu 24.04 is already old and most likely won't get updated.

2024-12-11 09:37 UTC, harlem88 approved these changes

2024-12-11 10:50 UTC, merged