Fetch and publish WiFiScanResults
edgehog-device-manager/edgehog-esp32-device pull request #11
Opened 2021-11-09 17:38 UTC by FrancescoVaiani

Add the capability to scan for APs and publish the relative data on Astarte.
The data is published as a datastream object. If multiple APs are found, consecutive messages with the same explicit timestamp will be sent.

Closes #10 

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2021-11-09 17:55 UTC, bettio requested changes

2021-11-09 17:55 UTC, bettio commented on src/edgehog.c
> +    const uint16_t DEFAULT_SCAN_LIST_SIZE = 5;
let's `#define` it at the beginning of this file, and let's leave a comment about it.

2021-11-09 17:55 UTC, bettio commented on src/edgehog.c
> +    esp_wifi_scan_start(&config, true);
this call is blocking, we can use this blocking function at the moment, however on the long term this is a bad idea, since it would block this thread for a significant amount of time.
If we are going to keep it, let's add a FIXME, otherwise we forget it and it will hurt us in the future.

2021-11-09 17:55 UTC, bettio commented on src/edgehog.c
> +        sprintf(mac, "%02x:%02x:%02x:%02x:%02x:%02x", ap_info[i].bssid[0], ap_info[i].bssid[1],
protip: always snprintf, this is a good habit against accidental buffer overflows.

2021-11-09 17:55 UTC, bettio commented on src/edgehog.c
> +        astarte_bson_serializer_append_string(&bs, "essid", (char *) ap_info[i].ssid);
why are we doing this cast? I can't understand it.

2021-11-10 11:33 UTC, harlem88 requested changes

2021-11-10 11:33 UTC, harlem88 commented on src/edgehog.c
> +    // this if statement could become a double annidated switch statement in the future
Check pointers before using them.

2021-11-10 12:00 UTC, harlem88 approved these changes

2021-11-10 16:04 UTC, bettio requested changes

2021-11-10 16:04 UTC, bettio commented on src/edgehog.c
> +    config.scan_time.active.max = 120;
struct initialization using braces would be better and safer than this. So let's do `config = { ... }`.
When doing this, we need to `memset` before.

2021-11-10 16:04 UTC, bettio commented on src/edgehog.c
> +            edgehog_device->astarte_device, wifi_ap.name, "/ap", doc, 0);
let's check if it is thread-safe or not

2021-11-10 16:14 UTC, bettio commented on src/edgehog.c
> +            edgehog_device->astarte_device, wifi_ap.name, "/ap", doc, 0);
yes, `esp_mqtt_client_publish` is thread-safe.

2021-11-10 16:32 UTC, FrancescoVaiani commented on src/edgehog.c
> +    ret = esp_wifi_scan_get_ap_num(&ap_count);
This is true if we want to retrieve and send all of the scanned networks. We use to limit the traffic data sending a number of messages equal to min(ap_count, DEFAULT_SCAN_LIST_SIZE). We can change this behaviour if you think the other way round should be preferable.

2021-11-10 17:03 UTC, bettio commented on src/edgehog.c
> +    ret = esp_wifi_scan_get_ap_num(&ap_count);
TBH I would send everything regardless of any other consideration, and discuss any further optimization on a second step.
The full list would be also useful when debugging a networking problem, so it might be required anyway.

2021-11-11 13:49 UTC, harlem88 approved these changes

2021-11-11 16:00 UTC, bettio requested changes

2021-11-11 16:00 UTC, bettio commented on src/edgehog.c
> +    wifi_ap_record_t ap_info[ap_count];
dynamically allocating memory on the stack is usually considered a dangerous habit

2021-11-11 16:00 UTC, bettio commented on src/edgehog.c
> +    wifi_ap_record_t ap_info[ap_count];
we should do calloc instead

2021-11-11 16:30 UTC, bettio requested changes

2021-11-11 16:30 UTC, bettio commented on src/edgehog.c
> +        return;
here we are leaking ap_info. Also we might log this error.

2021-11-11 16:30 UTC, bettio commented on src/edgehog.c
> +        return;
let's log this

2021-11-11 17:24 UTC, bettio approved these changes

2021-11-11 17:24 UTC, merged