Add support to LedBehavior
edgehog-device-manager/edgehog-esp32-device pull request #33
Opened 2021-12-17 14:37 UTC by FrancescoVaiani

- Add support to the parametric datastream path `/%{led_id}/behavior` of the `io.edgehog.devicemanager.LedBehavior` server-owned datastream interface.
At the current state, the only supported `led_id` is `indicator`.
The supported values are the following:

| value | behavior | Duration |
| --- | --- | --- |
| Blink60Seconds | Blink | 60 sec. |
| DoubleBlink60Seconds | Double blink | 60 sec. |
| SlowBlink60Seconds | Slow blink | 60 sec. |

- Add a Kconfig file for the edgehog-esp32-device component containing two configs:
    - `INDICATOR_GPIO_ACTIVATION`: `boolean` activate the indicator LED behavior support
    - `INDICATOR_GPIO`: [depends on `INDICATOR_GPIO_ACTIVATION`] `int` set the indicator LED GPIO number.

Close #29 

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2021-12-21 10:55 UTC, harlem88 requested changes

2021-12-21 10:55 UTC, harlem88 commented on private/edgehog_led.h
> +#define EDGEHOG_APP_EDGEHOG_LED_H
Remove `EDHEHOG_APP`. 
`EDGEHOG_APP_EDGEHOG_LED_H -> EDGEHOG_LED_H`

2021-12-21 10:55 UTC, harlem88 commented on private/edgehog_led.h
> +    ON = 0,
Move the above enum item comment here, like 
`ON = 0, /**< Always ON - Only for Default behavior */`

2021-12-21 10:55 UTC, harlem88 commented on private/edgehog_led.h
> +#endif // EDGEHOG_APP_EDGEHOG_LED_H
newline missing

2021-12-21 10:55 UTC, harlem88 commented on src/edgehog_led.c
> +#define STACK_SIZE 2048
move this above 
```static const char *TAG = "EDGEHOG_LED_BEHAVIOR";```

2021-12-21 10:55 UTC, harlem88 commented on src/edgehog_led.c
> +            vTaskDelete(led_manager->task_handle);
Check task_handle is null, because Passing NULL will cause the calling task to be deleted.

2021-12-21 10:55 UTC, harlem88 commented on src/edgehog_led.c
> +    led_manager->current_config = malloc(sizeof(led_behaviour_config_t));
check if current_config is not null.

2021-12-21 17:38 UTC, harlem88 requested changes

2021-12-21 17:38 UTC, harlem88 commented on src/edgehog_led.c
> +    led_behavior_handle->default_behavior = OFF;
Check `led_behavior_handle` is not null

2021-12-21 17:38 UTC, harlem88 commented on src/edgehog_led.c
> +        return EDGEHOG_ERR_TASK_CREATE;
If the task is not created, perhaps it should be free `led_manager->current_config`, because the only free that I see is into `blinkTaskCode`.

2021-12-22 12:32 UTC, bettio requested changes

2021-12-22 12:32 UTC, bettio commented on src/edgehog_led.c
> +        ESP_LOGE(TAG, "Unable to handle led behavior request, type not supported");
"Unable to handle led behavior request on %s, type code %i not supported", event_request->path, event_request->bson_value_type

2021-12-22 12:32 UTC, bettio commented on src/edgehog_led.c
> +    }
we might even pack together the 2 checks, so
```
if (event_request->bson_value_type != BSON_TYPE_STRING || strcmp(event_request->path, "/indicator/behaviour") != 0) {
... "Unable to handle led behavior request on %s with type code %i", event_request->path, event_request->bson_value_type
```

2021-12-22 12:32 UTC, bettio commented on src/edgehog_led.c
> +
idea: what about, behaviorNames = {"Blink60Seconds", "DoubleBlink60Seconds", ...} and if we keep in sync with the enum value we can even just iterate and return the index as the enum value.

2021-12-22 12:32 UTC, bettio commented on src/edgehog_led.c
> +edgehog_err_t set_led_behavior(edgehog_led_behaviour_manager_handle_t led_manager,
is it useful having this function as a public function? shouldn't we keep it static?

2021-12-22 12:32 UTC, bettio commented on Kconfig
> +config INDICATOR_GPIO_ACTIVATION
INDICATOR_GPIO_ACTIVATION -> INDICATOR_GPIO_ENABLE

2021-12-22 16:31 UTC, harlem88 approved these changes

2022-01-10 14:44 UTC, harlem88 approved these changes

2022-01-13 18:15 UTC, bettio requested changes

2022-01-17 17:44 UTC, bettio approved these changes

2022-01-17 17:44 UTC, merged