Telemetry config update
edgehog-device-manager/edgehog-esp32-device pull request #34
Opened 2021-12-20 18:27 UTC by harlem88

2022-01-11 18:16 UTC, bettio requested changes

2022-01-11 18:16 UTC, bettio commented on src/edgehog_telemetry.c
> +            if (!strstr(info.key, TASK_NAME_PREFIX)) {
I usually I go for `strncmp` when dealing with prefixes:
```c
strncmp(info.key, TASK_NAME_PREFIX, strlen(TASK_NAME_PREFIX))
```

2022-01-12 15:53 UTC, bettio requested changes

2022-01-12 15:53 UTC, bettio commented on src/edgehog_device.c
> +telemetry_type_t get_telemetry_type(const char *interface_name)
We always prefix all our function names in order to avoid symbol name clashes.

2022-01-12 15:53 UTC, bettio commented on include/edgehog_device.h
> +    EDGEHOG_TL_HW_INF0, /**< The hardware info telemetry type. */
@harlem88 do you hate human kind? :sweat_smile:

2022-01-12 16:56 UTC, bettio requested changes

2022-01-12 16:56 UTC, bettio commented on include/edgehog_device.h
> +    EDGEHOG_TL_INVALID = 0, /**< The telemetry type is invalid. */
let's never we worries about long names, so let's call it EDGEHOG_TELEMETRY_INVALID and etc.

2022-01-12 16:56 UTC, bettio commented on src/edgehog_telemetry.c
> +    if (event_request->bson_value_type != BSON_TYPE_STRING || event_request->path) {
let's use the validate macro if possible.

2022-01-12 16:56 UTC, bettio commented on src/edgehog_telemetry.c
> +    strtok((char *) event_request->path, "/"); // skip /request
I think we should usually prefer reentrant version, which is `strtok_r`.

2022-01-12 16:56 UTC, bettio commented on src/edgehog_telemetry.c
> +error:
let's avoid using labels and gotos when they are no needed (we don't have any cleanup here).

2022-01-17 18:35 UTC, bettio requested changes

2022-01-17 18:35 UTC, bettio commented on private/edgehog_device_private.h
> +typedef void (*telemetry_routine)(edgehog_device_handle_t edgehog_device);
this is a callback, so I would call it `telemetry_callback`. @rbino any naming feedback here?

2022-01-17 18:35 UTC, bettio commented on private/edgehog_device_private.h
> +telemetry_routine edgehog_device_get_telemetry_routine(telemetry_type_t type);
See above here.

2022-01-17 18:35 UTC, bettio commented on src/edgehog_telemetry.c
> +}
it can be avoided if you just do:
```
typedef enum
{
    EDGEHOG_TELEMETRY_INVALID = 0, /**< The telemetry type is invalid. */
    EDGEHOG_TELEMETRY_HW_INFO = 1, /**< The hardware info telemetry type. */
    EDGEHOG_TELEMETRY_WIFI_SCAN = 2, /**< The wifi scan telemetry type. */
    EDGEHOG_TELEMETRY_SYSTEM_STATUS = 3 /**< The system status telemetry type. */
} telemetry_type_t;
```
By the way I didn't check if C std mandates sequential/well-defined integer values for enums, if so, it is not required.

2022-01-19 17:52 UTC, bettio requested changes

2022-01-19 17:52 UTC, bettio commented on src/edgehog_telemetry.c
> +    char enanle_key[TASK_NAME_SIZE];                                                               \
I think there is a typo here: `enanle_key`.

2022-01-19 17:52 UTC, bettio commented on src/edgehog_telemetry.c
> +#define GET_TELEMETRY_TYPE(telemetry_index) telemetry_index + 1
we should always have parenthesis around macros. Also I'd add a cast.

2022-01-19 17:52 UTC, bettio commented on src/edgehog_telemetry.c
> +#define TASK_NAME_SIZE 8
where this 8 comes from?

2022-01-19 18:45 UTC, harlem88 commented on src/edgehog_telemetry.c
> +#define TASK_NAME_SIZE 8
It is the task_name_prefix +  telemetry_type_t to_string, but it can be decrement to 6.

2022-01-20 09:11 UTC, bettio approved these changes

2022-01-20 09:11 UTC, merged