Decouple new instance from first data send
edgehog-device-manager/edgehog-esp32-device pull request #69
Opened 2022-04-29 12:53 UTC by FrancescoVaiani

Having both the initial setup and the first data sent in the `edgehog_device_new` could make it a little hard to integrate with other modules that make use of the Astarte SDK.
Move the first data sent to `edgehog_device_start` should make it easier.

Close #68 

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2022-04-29 13:08 UTC, harlem88 commented on src/edgehog_device.c
> +static void edgehog_first_publish(edgehog_device_handle_t edgehog_device)
I'm not sure about this name, maybe it should be called `edgehog_init`, keeping it private anyway.

2022-04-29 13:22 UTC, harlem88 requested changes

2022-04-29 13:22 UTC, harlem88 commented on src/edgehog_device.c
> +    edgehog_init(edgehog_device);
Move this to the first line of `edgehog_device_start` function, the init function should be called before telemetry start.

2022-04-29 13:25 UTC, harlem88 approved these changes

2022-05-13 15:26 UTC, bettio requested changes

2022-05-17 09:54 UTC, bettio approved these changes

2022-05-17 09:54 UTC, merged