Support to idf 5.0
edgehog-device-manager/edgehog-esp32-device pull request #79
Opened 2023-03-31 13:09 UTC by sorru94

2023-03-31 13:33 UTC, sorru94 commented on .github/workflows/build.yaml
> +      - '*'
Remember to remove once CI has been enabled.

2023-03-31 13:39 UTC, harlem88 requested changes

2023-04-03 09:47 UTC, harlem88 commented
Add this lines to the Changelog:

## [0.7.0] - Unreleased
### Added
- Add support to ESP-IDF v5.0

2023-04-03 13:08 UTC, harlem88 commented on CHANGELOG.md
> +- Add support to ESP-IDF v5.0
```suggestion
- Add support to ESP-IDF v5.0.
```

2023-04-03 13:11 UTC, harlem88 approved these changes

2023-04-03 13:17 UTC, merged