Fixes for example
edgehog-device-manager/edgehog-esp32-device pull request #83
Opened 2023-04-18 08:44 UTC by sorru94

Fixes the example, adding the required configuration options and doing some generic clean up.

2023-04-18 09:11 UTC, harlem88 requested changes

2023-04-18 09:11 UTC, harlem88 commented on examples/edgehog_app/main/include/example_task.h
> +#define EXAMPLE_TASK_H
Leave a new line between the license and code.
```suggestion
 */

#ifndef EXAMPLE_TASK_H
#define EXAMPLE_TASK_H
```

2023-04-18 09:11 UTC, harlem88 commented on examples/edgehog_app/main/include/wifi_cfg.h
> +#ifndef WIFI_CFG_H
same above
```suggestion

#ifndef WIFI_CFG_H
```

2023-04-18 09:11 UTC, harlem88 commented on examples/edgehog_app/main/src/wifi_cfg.c
> +#include "wifi_cfg.h"
```suggestion
 */
 
#include "wifi_cfg.h"
```

2023-04-19 10:06 UTC, sorru94 commented on examples/edgehog_app/main/src/example_task.c
> +#include "example_task.h"
This conflicts with the used configuration for `clang-format`.

2023-04-20 16:15 UTC, harlem88 approved these changes

2023-04-20 16:16 UTC, merged