Publish OS runtime
edgehog-device-manager/edgehog-esp32-device pull request #9
Opened 2021-11-05 17:48 UTC by harlem88

2021-11-08 16:37 UTC, FrancescoVaiani commented on src/edgehog.c
> +            hardware_info_interface.name, ret);
qui dovrebbe essere `os_runtime_status_interface.name` e non `hardware_info_interface.name`

2021-11-08 19:04 UTC, bettio requested changes

2021-11-08 19:04 UTC, bettio commented on src/edgehog.c
> +    int task_count = (int) uxTaskGetNumberOfTasks();
I don't understand why you are doing this cast.

2021-11-08 19:04 UTC, bettio commented on src/edgehog.c
> +}
missing new line at the end of file.

2021-11-08 19:04 UTC, bettio commented on src/edgehog.c
> +edgehog_device_handle_t edgehog_init(astarte_device_handle_t astarte_device)
let's call it `edgehog_new` since we are allocating memory, otherwise `edgehog_init` if we initialize already allocated memory.

2021-11-09 14:18 UTC, FrancescoVaiani requested changes

2021-11-09 14:18 UTC, FrancescoVaiani commented on src/edgehog.c
> +        astarte_device, hardware_info_interface.name, "/mem/totalBytes", mem_total_bytes, 2);
I think we have a little regression here. This lines should be `astarte_device_set_[type]_property` as for previous commit.

2021-11-09 15:46 UTC, bettio approved these changes

2021-11-09 15:46 UTC, bettio commented on src/edgehog.c
> +void publish_system_status(edgehog_device_handle_t edgehog_device);
these functions are not exposed in the .h file, so I suppose they are private. In that case I would mark them as static so their symbol in not exported outside the object file.

2021-11-09 15:46 UTC, bettio commented on include/edgehog.h
> + * @details This function has to be called to create the device SDK before doing anything else.
I think we might rephrase it in a better way.

2021-11-09 15:46 UTC, bettio commented on src/edgehog.c
> +    uint32_t avail_memory = esp_get_minimum_free_heap_size();
I think here we should call `esp_get_free_heap_size()`, `esp_get_minimum_free_heap_size()` looks like a monotonic minimum. So let's check the documentation twice.

2021-11-09 15:49 UTC, bettio requested changes
there are some minor issues that need to be fixed.

2021-11-09 16:46 UTC, bettio approved these changes

2021-11-09 16:48 UTC, FrancescoVaiani approved these changes

2021-11-09 16:48 UTC, merged